POST http://localhost:8080/usuarios
Content-Type: application/json

{
    "nome": "Augusto",
    "email": "70rr40@gmail.com",
    "senha": "123456"
}
###
GET http://localhost:8080/usuarios
Content-Type: application/json